#!/usr/bin/env php
<?php
# Git Prepare Commit Message Hook Script
#
# Location: <repository>/.git/hooks/prepare-commit-msg
#
# This script will automatically add the correct
# JIRA ISSUE ID to the beginning of each commit message
# When the branch ID is starts with the JIRA ISSUE ID.
# It can be overridden if specified in the message.
#
# Example:
#
# jira-123_branch_name => 'JIRA-123 commit message'
#
# @author Tamas Kalman <ktamas77@gmail.com>

$messageFile = $argv[1];
$message = file_get_contents($messageFile);
$currentBranchName = exec('git rev-parse --abbrev-ref HEAD');
$message = sprintf('[%s] %s', strtoupper($currentBranchName), $message);
file_put_contents($messageFile, $message);
